# Generated by Django 3.0.7 on 2020-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature_store',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
