# Generated by Django 3.0.7 on 2020-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_profile_pref_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature_store',
            field=models.TextField(blank=True, max_length=650000),
        ),
    ]
