# Generated by Django 3.0.7 on 2020-06-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature_store',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
